CREATE TABLE USER_ROLES (
    ID INT NOT NULL AUTO_INCREMENT,
    ROLES VARCHAR(20),
    PRIMARY KEY (ID)
);

CREATE TABLE USERS_DETAILS (
    ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME varchar(200),
    LAST_NAME varchar(255),
    PHONE_NUMBER varchar(255),
    GENDER varchar(255),
    EMAIL_ID varchar(255),
    USER_ID varchar(255),
    PASSWORD varchar(255),
    PRIMARY KEY (ID)
);
